### ISSUE TITLE
parser does not accept messages larger than 65kilobytes

### ISSUE THREAD

**Issue by agis** [secmask/go-redisproto#3]
Currently a superficial the parser cannot read messages larger than 65kb, an artificial limit imposed in these lines: https://github.com/secmask/go-redisproto/blob/master/parser.go#L20.

However, the [Redis protocol](https://redis.io/topics/protocol) specifies that strings might be up to 512MB. The redis-rb driver, for example, works with strings even larger than 512MB.  Furthermore, there are plans to even remove this limit from the server (see https://github.com/antirez/redis/issues/757).

However, go-redisproto currently returns an "Invalid bulk size" error. Is there any reason for this limitation?

**Comment by secmask** [comment]
hello, the limit was designed for this 

> client errors that will output a nonsensical bulk length and will fill the server

but that limit actually a public variable and you can set it to any value you need before you create a Parser, this also true for other Max... variable.

**Comment by agis** [comment]
Thanks for the clarification. Closing this as a non-issue.

**Comment by agis** [comment]
@secmask Side: Is there any reason why these errors are not of type `ProtocolError{}`?

**Comment by secmask** [comment]
at the beginning I think that I can make some specified kind of errors(called ProtocolError) where we can still use the current connection after the error, but for now I think it's not safe enough to do that, we should finish the current connection(write a error response and close it) for any kind of error. So it should not matter now.
